_core:
  default_config_hash: dB-OhBLFamIxgLKgeBLgC34eFBdtPKMyCJV62kwYads
libros:
  -
    titulo: 'El Quijote'
    autor: 'Miguel de Cervantes'
    año: 1605
  -
    titulo: 'Cien años de soledad'
    autor: 'Gabriel García Márquez'
    año: 1967
  -
    titulo: '1984'
    autor: 'George Orwell'
    año: 1949
